### ISSUE TITLE
1.14.1 Error Paper-spigot

### ISSUE THREAD

**Issue by darksaid98** [RifleDLuffy/RFChairs#6]
Spigot-api-version: 1.14.1-R0.1-SNAPSHOT
RFChairs version: 5.3
Paper-version: 1.14.1 Build-39

```
[RFChairs] Plugin RFChairs v5.3 generated an exception while executing task 1815
java.lang.NoClassDefFoundError: org/apache/commons/io/IOUtils
at com.rifledluffy.chairs.updating.Updater.getLastUpdate(Updater.java:24) ~[?:?]
at com.rifledluffy.chairs.ChairManager$1.run(ChairManager.java:472) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.1.jar:git-Paper-39]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.1.jar:git-Paper-39]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.1.jar:git-Paper-39]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

No idea why I got this but it just popped up after start so thought I'd inform you. Other than that everything seems to work normally.

**Comment by TheCompieter** [comment]
it's because this plugin doesn't work on 1.114.2 i got the same thing

[22:37:36 WARN]: [RFChairs] Plugin RFChairs v5.3 generated an exception while executing task 462
java.lang.NoClassDefFoundError: org/apache/commons/io/IOUtils
        at com.rifledluffy.chairs.updating.Updater.getLastUpdate(Updater.java:24) ~[?:?]
        at com.rifledluffy.chairs.ChairManager$1.run(ChairManager.java:472) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.2.jar:git-Paper-94]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.2.jar:git-Paper-94]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.2.jar:git-Paper-94]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_211]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
